# This workflow runs when commits are pushed to main or a branch starting with
# "version-". It checks if any packages require a new release, and if so,
# creates the corresponding crates.io releases and git tags.
name: Release
on:
  push:
    branches:
      - main
      - version-*
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo xtask auto-release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
